apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: etudiant23-ns # VOTRE NAMESPACE UNIQUE
type: Opaque
data:
  DB_USERNAME: cm9vdA== # 'root' encodé en Base64
  DB_PASSWORD: MTIxMg== # '1212' encodé en Base64