apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: etudiant23-ns # VOTRE NAMESPACE UNIQUE
spec:
  selector:
    app: mariadb-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP