apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-api # Cible les Pods créés par le Deployment
  type: NodePort # Permet d'accéder au Service depuis l'extérieur du cluster local
  ports:
    - protocol: TCP
      port: 8080 # Port exposé par le Service (interne au cluster)
      targetPort: 8080 # Port sur lequel l'application tourne dans le Pod
      # NodePort sera automatiquement assigné (généralement dans la plage 30000-32767)